### ISSUE TITLE
If the password contains `%` the `ConfigParser` fail

### ISSUE THREAD

**Issue by simone-viozzi** [Ac5000/lemmy_account_sync#4]
Solution: https://stackoverflow.com/a/47640849/8069500

> If I replace ConfigParser with RawConfigParser everything is fine.

**Comment by Ac5000** [comment]
I will look into this when I get time to look at the other couple open issues as well. Thank you for submitting this, I'll close it once I have it fixed.

**Comment by Ac5000** [comment]
@simone-viozzi The issue should be resolved now. I was able to make a password with `%` on the enterprise.lemmy.ml instance and the app was able to log me in.

Thank you for finding and submitting this! Marking this as closed with the referenced commit. 

Feel free to open another issue if you run into something else.
